Added T8_ECLASS_INVALID
holke/t8code pull request #230
Opened 2022-05-03 18:54 UTC by Davknapp

T8_ECLASS_INVALID was added to the enumerator t8_eclass to be used for the case t8code does not support a type of element that is used by a third-party library, for example vtk. As all other eclasses already have a meaning, this new class is introduced.

**_All these boxes must be checked by the reviewers before merging the pull request:_**

- [ ] The author added a BSD statement to `doc/` (or already has one)
- [ ] The code compiles without warning in debugging and release mode, with and without MPI (this should be executed automatically in a github action)

  If the Pull request indroduces code that is not covered by the github action (for example coupling with a new library):
  - [ ] Should this use case be added to the github action?
  - [ ] If not, does the specific use case compile and all tests pass (check manually)

- [ ] All tests pass (in various configurations, this should be executed automatically in a github action)
- [ ] New source/header files are properly added to the Makefiles
- [ ] The reviewer executed the new code features at least once and checked the results manually
- [ ] The code is covered in an existing or new test case
- [ ] The code follows the [t8code coding guidelines](https://github.com/holke/t8code/wiki/Coding-Guideline)
- [ ] The code is well documented
- [ ] All function declarations, structs/classes and their members have a proper doxygen documentation
- [ ] All new algorithms and data structures are sufficiently optimal in terms of memory and runtime (If this should be merged, but there is still potential for optimization, create a new issue)
- [ ] Testing of this template: If you feel something is missing from this list, contact the developers

2022-05-04 07:53 UTC, holke commented
good change.
Please add a small test to the eclass test. We should at least check that T8_ECLASS_INVALID is not equal to any other class (and not ECLASS_COUNT) and that iterating from ECLASS_FIRST to ECLASS_COUNT does not give an invalid class.

Additionally, we should add a function `t8_eclass_is_valid(eclass)` returning 0 or non-0 when the class is valid.

2022-05-04 16:51 UTC, holke requested changes
Nice :)
 only a minor edit regarding the doxygen comment.

Next time please do not commit indented code that does not belong to the PR. (using git add -p)
You can make an extra PR for the indentation of other code.

2022-05-04 16:51 UTC, holke commented on test/t8_gtest_eclass.cxx
> +  }
```suggestion
  }
  EXPECT_FALSE (t8_eclass_is_valid (T8_ECLASS_INVALID));
```

2022-05-04 16:54 UTC, holke commented
Thinking about this...what about T8_ECLASS_COUNT.
This also is no valid eclass, so t8_eclass_is_valid should return 0 here, shouldnt it?

2022-05-05 06:49 UTC, Davknapp commented on src/t8_eclass.h
> + * \param [in] eclass    The eclass to check.
Added the documentation

2022-05-05 06:49 UTC, Davknapp commented
> Thinking about this...what about T8_ECLASS_COUNT. This also is no valid eclass in the sense that calling an eclass function with T8_ECLASS_COUNT as input generally is not defined. So t8_eclass_is_valid should return 0 here as well, shouldnt it?

I agree with you and adapted the function accordingly

2022-05-05 07:58 UTC, holke commented on src/t8_eclass.h
> +/** Check, if a class is a valid class. Returns non-zero if it is a valid class,
```suggestion
/** Check whether a class is a valid class. Returns non-zero if it is a valid class,
```

2022-05-05 10:18 UTC, holke approved these changes

2022-05-05 10:22 UTC, merged