Fix include dir
holke/t8code pull request #248
Opened 2022-05-13 16:19 UTC by holke

**_Describe your changes here:_**

Continues previous PR #153.

This change applies to what happens when we `make install` t8code.
Previously all headers were put into `include/t8`.
Now, all headers are put into `include` directly respecting the subfolder structure of t8code.
Thus, if a header is in the source foldert `src/folder/header.h` then it is installed to `include/folder/header.h`.

The folder structure of `include/` should now mirror the folder structure of `src/` (ignoring sc and p4est files).

**_All these boxes must be checked by the reviewers before merging the pull request:_**

- [ ] The author added a BSD statement to `doc/` (or already has one)
- [ ] The code compiles without warning in debugging and release mode, with and without MPI (this should be executed automatically in a github action)

  If the Pull request indroduces code that is not covered by the github action (for example coupling with a new library):
  - [ ] Should this use case be added to the github action?
  - [ ] If not, does the specific use case compile and all tests pass (check manually)

- [ ] All tests pass (in various configurations, this should be executed automatically in a github action)
- [ ] New source/header files are properly added to the Makefiles
- [ ] The reviewer executed the new code features at least once and checked the results manually
- [ ] The code is covered in an existing or new test case
- [ ] The code follows the [t8code coding guidelines](https://github.com/holke/t8code/wiki/Coding-Guideline)
- [ ] The code is well documented
- [ ] All function declarations, structs/classes and their members have a proper doxygen documentation
- [ ] All new algorithms and data structures are sufficiently optimal in terms of memory and runtime (If this should be merged, but there is still potential for optimization, create a new issue)
- [ ] Testing of this template: If you feel something is missing from this list, contact the developers

2022-05-25 10:41 UTC, Davknapp reviewed
Please address my question, I do not understand that part of the Makefile.
Apart from that it is ready to merge!

2022-05-25 10:41 UTC, Davknapp commented on src/Makefile.am
> +libt8_installed_headers_schemes_default =
Why are these empty?

2022-05-27 06:28 UTC, Davknapp commented on src/Makefile.am
> +libt8_installed_headers_schemes_default =
Thx for the explanation! At first, I thaught it was a doubling.

2022-05-27 06:30 UTC, Davknapp requested changes
Please solve the remaining merge-conflicts, then we are ready to merge!

2022-06-02 08:05 UTC, holke commented
Done

2022-06-20 10:49 UTC, Davknapp approved these changes

2022-06-20 10:49 UTC, merged